[package]
name = "gobbind-macros"
description = "#[gobbind] macro"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
proc-macro-error2.workspace = true
syn = { workspace = true, features = ["full"] }
quote.workspace = true
