name: Lint
on: [push, pull_request]

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint-win:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2026-08-01
          components: rustfmt, clippy
      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        run: cargo fmt --check
      - name: Run Clippy
        run: cargo clippy --all-features

  lint-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2026-08-01
          components: rustfmt, clippy
      - name: Setup cache
        uses: Swatinem/rust-cache@v2

      - name: Run rustfmt
        run: cargo fmt --check
      - name: Run Clippy
        run: cargo clippy --all-features
